### ISSUE TITLE
Error when setting up kong

### ISSUE THREAD

**Issue by Maghnie** [N5GEH/n5geh.tutorials.api-protection#3]
When following the readme instructions, one of the docker containers keeps restarting after step 2:
![image](https://user-images.githubusercontent.com/68941589/224056583-8233bfff-f88a-4921-a85b-410f90ea3da3.png)

This is part of the container log messages:
[kong_container_logs.txt](https://github.com/N5GEH/n5geh.tutorials.api-protection/files/10932602/kong_container_logs.txt)

The logs first mention a privilege issue, but running the commands as admin/sudo didn't make a difference.

There's also a `'kong.plugins.base_plugin' not found` error mentioned - is this known or are there any hints how to solve it?

**Comment by hebbarguru2** [comment]
@Maghnie I believe the issue is that kong custom plugins are of old version. 
base_plugin is deprecated from kong v3.x.x , and the plugins are recently updated. 
Use this [link deleted] repo to clone and checkout to development branch to build the images. Will soon merge it to master
